const http = require('http')
http.createServer((req, res) => {
    // res.writeHead( 200, {'content-type': 'application/json'})
    // res.setHeader('Content-Disposition', 'attachment; filename=lista.csv')
    // res.writeHead( 200, {'Content-Type': 'application/csv'})
    // res.write('id, nombre\n')
    // res.write('1, Algore\n')
    // res.write('2, Bush\n')
    // res.write('3, Obama\n')
    res.write('Hola Mundo')
    res.end()
})
.listen( 8080 )

console.log('Escuchando en el puerto: ', 8080)